version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  web:
    build: ./django
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: '1'
    env_file:
      - ./envs/postgres.env
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
