# Generated by Django 5.1 on 2024-09-06 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2, verbose_name={'AC': 'AC', 'AL': 'AL', 'AM': 'AM', 'AP': 'AP', 'BA': 'BA', 'CE': 'CE', 'DF': 'DF', 'ES': 'ES', 'GO': 'GO', 'MA': 'MA', 'MG': 'MG', 'MS': 'MS', 'MT': 'MT', 'PA': 'PA', 'PB': 'PB', 'PE': 'PE', 'PI': 'PI', 'PR': 'PR', 'RJ': 'RJ', 'RN': 'RN', 'RO': 'RO', 'RR': 'RR', 'RS': 'RS', 'SC': 'SC', 'SE': 'SE', 'SP': 'SP', 'TO': 'TO'})),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('address_type', models.CharField(max_length=2, verbose_name={'AV': 'Avenida', 'BE': 'Beco', 'ES': 'Estrada', 'RO': 'Rodovia', 'RU': 'Rua', 'VE': 'Via expressa'})),
                ('cep', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=15)),
                ('complement', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['city'],
            },
        ),
    ]
