# Generated by Django 5.1 on 2024-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.CharField(max_length=2, verbose_name={'AD': 'Administração', 'CI': 'Comunicação Interna', 'DS': 'Design', 'EC': 'E-commerce', 'FC': 'Financeiro', 'JD': 'Jurídico', 'MK': 'Marketing', 'PA': 'Planejamento e Análise de Negócios', 'PD': 'Pesquisa e Desenvolvimento', 'RH': 'Recursos Humanos', 'SD': 'Saúde', 'SG': 'Serviços Gerais', 'TI': 'Tecnologia da Informação', 'VD': 'Vendas'}),
        ),
    ]
